/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/runtime";
import { STENCIL_SIGNALS_SYMBOL, type ReadonlySignal } from "@stencil/core/signals";
export { STENCIL_SIGNALS_SYMBOL } from "@stencil/core/signals";
import { Item } from "./issue2-jsx-types-reject-signal/target";
export { Item } from "./issue2-jsx-types-reject-signal/target";
export namespace Components {
    interface IssueOne {
    }
    interface IssueThree {
    }
    /**
     * An ordinary component with ordinary typed props.
     */
    interface IssueTwoTarget {
        /**
          * @default []
         */
        "items": Item[];
        "label": string;
    }
}
declare global {
    interface HTMLIssueOneElement extends Components.IssueOne, HTMLStencilElement {
    }
    var HTMLIssueOneElement: {
        prototype: HTMLIssueOneElement;
        new (): HTMLIssueOneElement;
    };
    interface HTMLIssueThreeElement extends Components.IssueThree, HTMLStencilElement {
    }
    var HTMLIssueThreeElement: {
        prototype: HTMLIssueThreeElement;
        new (): HTMLIssueThreeElement;
    };
    /**
     * An ordinary component with ordinary typed props.
     */
    interface HTMLIssueTwoTargetElement extends Components.IssueTwoTarget, HTMLStencilElement {
        readonly [STENCIL_SIGNALS_SYMBOL]?: ReadonlyMap<"label" | "items", ReadonlySignal<unknown>>;
    }
    var HTMLIssueTwoTargetElement: {
        prototype: HTMLIssueTwoTargetElement;
        new (): HTMLIssueTwoTargetElement;
    };
    interface HTMLElementTagNameMap {
        "issue-one": HTMLIssueOneElement;
        "issue-three": HTMLIssueThreeElement;
        "issue-two-target": HTMLIssueTwoTargetElement;
    }
}
declare namespace LocalJSX {
    interface IssueOne {
    }
    interface IssueThree {
    }
    /**
     * An ordinary component with ordinary typed props.
     */
    interface IssueTwoTarget {
        /**
          * @default []
         */
        "items"?: Item[];
        "label"?: string;
    }

    interface IssueTwoTargetAttributes {
        "label": string;
    }

    interface IntrinsicElements {
        "issue-one": IssueOne;
        "issue-three": IssueThree;
        "issue-two-target": Omit<IssueTwoTarget, keyof IssueTwoTargetAttributes> & { [K in keyof IssueTwoTarget & keyof IssueTwoTargetAttributes]?: IssueTwoTarget[K] } & { [K in keyof IssueTwoTarget & keyof IssueTwoTargetAttributes as `attr:${K}`]?: IssueTwoTargetAttributes[K] } & { [K in keyof IssueTwoTarget & keyof IssueTwoTargetAttributes as `prop:${K}`]?: IssueTwoTarget[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "issue-one": LocalJSX.IntrinsicElements["issue-one"] & JSXBase.HTMLAttributes<HTMLIssueOneElement>;
            "issue-three": LocalJSX.IntrinsicElements["issue-three"] & JSXBase.HTMLAttributes<HTMLIssueThreeElement>;
            /**
             * An ordinary component with ordinary typed props.
             */
            "issue-two-target": LocalJSX.IntrinsicElements["issue-two-target"] & JSXBase.HTMLAttributes<HTMLIssueTwoTargetElement>;
        }
    }
}
